// <auto-generated />
using ForumAppDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumAppDemo.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20221001132833_IsDeletedFlagAdded")]
    partial class IsDeletedFlagAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumAppDemo.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Post Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Content");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Marks records as deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Post title");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasComment("Publish Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is my first post",
                            IsDeleted = false,
                            Title = "My first post"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is my second post and more",
                            IsDeleted = false,
                            Title = "My second post"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is my third post whatever",
                            IsDeleted = false,
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
